### ISSUE TITLE
Status inititial thresholds seem incorrect

### ISSUE THREAD

**Issue by Daykeras** [RoboMechE/MHRise-Database#1]
The status initial thresholds for 1P HR quests do not match observed initial thresholds.

If you use a bow gun to poison an HR Zinogre it takes 4 shots of 40 poison ammo to apply. Not the 5 that 195 initial threshold would suggest. 

My testing for status suggests that the initial thresholds are equal to base and do no change regardless of HR or player count. 

Similarly Toadversary poison and ko thresholds do not appear accurate.

**Comment by RoboMechE** [comment]
Thank you for the info. I havent had the chance to test that much, but I was just noticing the inconsistency the other day. There are 2 fields in the data related to elementA and elementB, it must be that they relate to normal status and the new elemental blights. There is likely an issue with multiplayer scaling for break thresholds too. There appears to be a separate modifier for breaks now.

**Comment by RoboMechE** [comment]
Toadversary thresholds appear to be accurate. Remember that the value decays over time; by the time you get your 5 shots of poison off it will have decayed by 1 or 2.

**Comment by Daykeras** [comment]
For Toadversary it appears that -5/10 really means -1/2 which is what
caused my misunderstanding.

Thank you for replying!

**Comment by RoboMechE** [comment]
yeah, np. Its really updating every clock cycle, its more accurately -0.5/s. The data shows it in the file as two fields decay value: 5 and decay time 10, which is why I show it this way, but it definitely leads to confusion. I will make a note of this on the next update as well to help clarify that.
